cad2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^discounts/', include('discounts.urls')),
    url(r'^pricerules/', include('pricerules.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^pr_api/', include('api_requests.urls')),
]

discounts/urls.py
from django.conf.urls import url

from . import views


app_name = 'discounts'
urlpatterns = [
    url(r'^details/(?P<price_rule_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create/(?P<price_rule_id>[0-9]+)/$' , views.create , name="create"),
]

pricerules/urls.py
from django.conf.urls import url

from . import views

app_name = 'pricerules'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$' , views.create , name="create"),
    url(r'^update/(?P<price_rule_id>[0-9]+)/$' , views.update , name="update"),
    url(r'^delete/(?P<price_rule_id>[0-9]+)/$' , views.delete , name="delete"),
]

discounts/forms.py
from django import forms

class DiscountForm(forms.Form):
    code = forms.CharField(label="code title" , max_length = 100)

discounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from discounts import services
from .forms import *
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def detail(request , price_rule_id):
    discounts_list = services.get_discounts(price_rule_id)
    print(discounts_list)
    context = {
        'price_rule_id' : price_rule_id ,
        'discounts_list' : discounts_list
    }
    return render(request, 'discounts/detail.html', context)

def create(request, price_rule_id):
    if request.method == "POST":
        form = DiscountForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data)
            new_discount_code = services.create_discount_code(form.cleaned_data)
            services.post_discount_code(new_discount_code, price_rule_id)
            return HttpResponseRedirect(reverse('discounts:detail' , args=(price_rule_id,)))
    else:
        form = DiscountForm()
    return render(request , 'discounts/create.html', { 'form' : form })

discounts/templates/discounts/create.html
Create a New Discount

<form class="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" name="" value="New DC">
</form>

discounts/templates/discounts/detail.html
Hello youre in Detail!
{% for discount in discounts_list.discount_codes %}
  <ul>
    <li><a href="">{{discount.id}}</a></li>
    <li>{{discount.code}}</li>
  </ul>
{% endfor %}
<p><a href="{% url 'discounts:create' price_rule_id %}">Create New Discount Code</a></p>
<p><a href="{% url 'pricerules:index' %}">Return to Price Rules</a></p>

discounts/templates/discounts/index.html
{% extends 'discounts/base.html' %}
Youre in INDEX
{% block content %}
  {% for price_rule in price_rule_list.price_rules %}
  <ul>
      <li><a href="{% url 'discounts:detail' price_rule.id %}">{{ price_rule.title}}</a></li>
      <li>{{ price_rule.id }}</li>
      <li><a href="{% url 'discounts:update_pr' price_rule.id %}">Update This Price Rule</a></li>
  </ul>
  {% endfor %}

  <a href="{% url 'discounts:new_pr' %}">Create New Price Rule</a>

  {{success}}
{% endblock %}

discounts/templates/discounts/new_pr.html
{% extends 'discounts/base.html' %}

{% block content %}
  Create a new Price Rule
  Currently, if target_type is shipping_line, then only each is accepted.
  <p>Prerequisite shipping cost range. Can only be used when target_type is shipping_line</p>
  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="" value="Create  ">
  </form>
{% endblock%}