cad2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^discounts/', include('discounts.urls')),
    url(r'^pricerules/', include('pricerules.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^pr_api/', include('api_requests.urls')),
]

discounts/urls.py
from django.conf.urls import url

from . import views


app_name = 'discounts'
urlpatterns = [
    url(r'^details/(?P<price_rule_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create/(?P<price_rule_id>[0-9]+)/$' , views.create , name="create"),
]

pricerules/urls.py
from django.conf.urls import url

from . import views

app_name = 'pricerules'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$' , views.create , name="create"),
    url(r'^update/(?P<price_rule_id>[0-9]+)/$' , views.update , name="update"),
    url(r'^delete/(?P<price_rule_id>[0-9]+)/$' , views.delete , name="delete"),
]

pricerules/forms.py
from django import forms
from .choices import *
from functools import partial
from datetimewidget.widgets import DateTimeWidget
import datetime
DateInput = partial(forms.DateInput, {'class': 'datepicker'})

class PriceRuleForm(forms.Form):
    starts_at = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'class': 'datetimepicker'}))
    ends_at = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'class': 'datetimepicker'}))
    title = forms.CharField(label="title", max_length = 50)
    target_type = forms.ChoiceField(choices = TARGET_TYPE_CHOICES, label="target type")
    target_selection = forms.ChoiceField(choices = TARGET_SELECTION_CHOICES, label="target selection")
    allocation_method = forms.ChoiceField(choices = ALLOCATION_METHOD_CHOICES, label = "allocation method")
    value_type = forms.ChoiceField(choices = VALUE_TYPE_CHOICES, label = "value type")
    value = forms.IntegerField(label="Value")
    once_per_customer = forms.ChoiceField(choices = ONCE_PER_CUSTOMER_CHOICES, label = "once per customer?")
    usage_limit = forms.IntegerField(label="Usage Limit")
    customer_selection = forms.ChoiceField(choices = CUSTOMER_SELECTION_CHOICES, label ="Customer Selection")
    # prerequisite_Subtotal_range = forms.IntegerField
    # prerequisite_shipping_price_range =
    # prerequisite_saved_search_ids
    # entitled_product_ids = forms.MultipleChoiceField(choices = PRODUCT_CHOICES, label="product ids []", required=False, widget=forms.CheckboxSelectMultiple)
    entitled_variant_ids = forms.MultipleChoiceField(label="Variant ID's",choices = VARIANT_CHOICES, required=False, widget=forms.CheckboxSelectMultiple)
    # entitled_collection_ids = forms.IntegerField(label="collection ids []", required=False)
    # entitled_country_ids = forms.IntegerField(label="country Ids []", required=False)

    def clean(self):
        form_data = self.cleaned_data
        if form_data['target_type'] == 'shipping_line' and form_data['allocation_method'] == 'each':
            self._errors['allocation_method'] = ["Allocation Method can only be 'each' when target_type is equal to line_item"]
            del form_data['allocation_method']
        if form_data['target_type'] != 'shipping_line' and form_data['value_type'] == 'percentage':
            self._errors['value_type'] = ['Target Type must be shipping_line in order for Value Type to be a percentage']
            del form_data['value_type']
        if form_data['value'] > 0:
            self._errors['value'] = ['Value must be less than 0']
            del form_data['value']
        if form_data['target_type'] == 'shipping_line' and form_data['value'] != -100:
            self._errors['value'] = ['While target_type is equal to shipping_line , value can only be equal to -100']
            del form_data['value']
        if form_data['usage_limit'] < 1 :
            self._errors['usage_limit'] = ['Usage Limit must be an integer over 0']
            del form_data['usage_limit']
        return form_data

pricerules/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from pricerules import services
from .forms import *
from django.contrib.auth.decorators import login_required
import json

@login_required
# Create your views here.
def index(request):
    price_rule_list = services.get_price_rules()
    # print(price_rule_list)
    # print(json.dumps(price_rule_list, indent=4, sort_keys=True))
    context = {
        'price_rule_list' : price_rule_list
    }
    return render(request, 'pricerules/index.html', context)

def create(request):
    if request.method == "POST":
        form = PriceRuleForm(request.POST)

        if form.is_valid():
            print(form.cleaned_data)
            new_price_rule = services.create_price_rule(form.cleaned_data)
            print(new_price_rule)
            new_price_rule_id = services.post_price_rule(new_price_rule)
            return HttpResponseRedirect(reverse('discounts:detail' , args=(new_price_rule_id,)))
        else:
            print('didnt work')
    else:
        form = PriceRuleForm()

    return render(request , 'pricerules/create.html', {'form' : form})

def update(request , price_rule_id):
    if request.method == "POST":
        form = PriceRuleForm(request.POST)
        if form.is_valid():
            print('form is valid')
            updated_price_rule = services.update_price_rule(form.cleaned_data)
            services.post_update_price_rule(updated_price_rule , price_rule_id)
            return render(request , 'pricerules/index.html')
        else:
            print(form.cleaned_data)
            print('form is invalid')
    else:
        print('request is not put')
        price_rule = services.get_single_price_rule(price_rule_id)

        form = PriceRuleForm(price_rule.get('price_rule'))
    return render(request , 'pricerules/update.html', { 'form': form })

def delete(request , price_rule_id):
    # ASK USER TO PROVIDE LOG IN CREDENTIALS
    print(price_rule_id)
    services.post_delete_price_rule(price_rule_id)
    return HttpResponseRedirect(reverse('pricerules:index'))

pricerules/templates/pricerules/create.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'pricerules/create.css' %}" />

  <form method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="pr-create-basic-info--background-color pr-create-basic-info col s5">
        <div class="form-wrap">
          <label for="">Starting Time</label>
          {{form.starts_at  }}
        </div>
        <div class="form-wrap">
          <label for="">Ending Time</label>
          {{form.ends_at }}
        </div>
        <div class="form-wrap">
          <label for="">Price Rule Title</label>
          {{form.title}}
        </div>
        <div class="form-wrap">
          <p class="pr-create-form-input-disclaimer">Target Type(The target type the price rule applies to.)</p>
          {{form.target_type}}
        </div>
        <div class="form-wrap">
          <p class="pr-create-form-input-disclaimer">Target Selection(The target selection method of the price rule. Use all to apply the discount to all line items in the checkout and use entitled to apply to selected entitlements.)</p>
          {{form.target_selection}}
        </div>
        <div class="form-wrap">
          <p class="pr-create-form-input-disclaimer">Allocation Method(With an allocation method of each, the discount will be applied to each of the entitled items. <br> With an allocation method of across, the calculated discount amount will be applied across the entitled items <span class="text-red">Currently, if target_type is shipping_line, then only each is accepted.</span>)</p>
          {{form.allocation_method}}
        </div>
        <div class="form-wrap">
          <p class="pr-create-form-input-disclaimer">Value Type(The value type of the price rule. <span class="text-red">If target_type is shipping_line then only percentage is accepted.</span>)</p>
          {{form.value_type}}
        </div>
        <div class="form-wrap">
          <label for="">Value(The value of the price rule. <span class="text-red">If target_type is shipping_line, then only -100 is accepted. It's important to note that when discounting a resource, the value must be a negative number.</span>)</label>
          {{form.value}}
        </div>
        <div class="form-wrap">
          <p class="pr-create-form-input-disclaimer">Once Per Customer?</p>
          {{form.once_per_customer}}
        </div>
        <div class="form-wrap">
          <label for="">Usage Limit</label>
          {{form.usage_limit}}
        </div>
        <div class="form-wrap">
          <p class="pr-create-form-input-disclaimer">Customer Selection(The customer selection for the price rule. <span class="text-red">A customer selection of all means there are no restrictions on who's eligible for the price rule.
A customer selection of prerequisite means a customer needs to belong to one of the specified prerequisite customer saved searches in prerequisite_saved_search_ids.</span>)</p>
          {{form.customer_selection}}
        </div>
        <input class="btn" type="submit" name="" value="Create">
      </div>
      <div class="pr-create-basic-info--background-color pr-create-basic-info col s6 offset-s1">
        <div class="form-wrap pr-create-variant-ids">
          <label for="">entitled_variant_ids</label>
          {{form.entitled_variant_ids}}
        </div>
      </div>
    </div>
  </form>
  <script type="text/javascript">
    $('input[name="entitled_variant_ids"]').each(function(){
        var that = $(this)
        that.insertBefore(that.closest('label'))
    })
    $('select').each(function(){
      var that = $(this);
      that.siblings('label').remove();
      that.closest('p').addClass('input-field');

    })
  </script>
{% endblock%}
{# <div class="form-wrap">
  <label for="">title</label>
  {{form.title}}
</div>
<div class="form-wrap">
  <label for="">target_type</label>
  {{form.target_type}}
</div>
<div class="form-wrap">
  <label for="">target_selection</label>
  {{form.target_selection}}
</div>
<div class="form-wrap">
  <label for="">allocation_method</label>
  {{form.allocation_method}}
</div>
<div class="form-wrap">
  <label for="">value_type</label>
  {{form.value_type}}
</div>
<div class="form-wrap">
  <label for="">value</label>
  {{form.value}}
</div>
<div class="form-wrap">
  <label for="">once_per_customer</label>
  {{form.once_per_customer}}
</div>
<div class="form-wrap">
  <label for="">usage_limit</label>
  {{form.usage_limit}}
</div>
<div class="form-wrap">
  <label for="">customer_selection</label>
  {{form.customer_selection}}
</div>
<div class="form-wrap">
  <label for="">entitled_product_ids</label>
  {{form.entitled_product_ids}}
</div>
<div class="form-wrap">
  <label for="">entitled_variant_ids</label>
  {{form.entitled_variant_ids}}
</div>
<div class="form-wrap">
  <label for="">entitled_collection_ids</label>
  {{form.entitled_collection_ids}}
</div>
<div class="form-wrap">
  <label for="">entitled_country_ids</label>
  {{form.entitled_country_ids}}
</div>
<div class="form-wrap">
  <label for="">starts</label>
  {{form.starts_at  }}
</div>
<div class="form-wrap">
  <label for="">ends_at</label>
  {{form.ends_at }}
</div>#}

pricerules/templates/pricerules/index.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'pricerules/index.css' %}" />

  <div class="pr-index-item pr-index-item--border">
    <table>
      <tr>
        <th><p>Price Rule Title</p></th>
        <th><p>Price Rule ID</p></th>
        <th><p>Price Rule Value Type</p></th>
        <th><p>Price Rule Value</p></th>
        <th><p>Price Rule Entitled Variants</p></th>
        <th><p>Price Rule Controls</p></th>
      </tr>
      {% for price_rule in price_rule_list.price_rules %}
        <tr>
          <td class=""><a href="{% url 'discounts:detail' price_rule.id %}">{{ price_rule.title}}</a></td>
          <td class="">{{ price_rule.id }}</td>
          <td class="">{{ price_rule.value_type }}</td>
          <td class="">{{ price_rule.value }}</td>
          <td><div class="waves-effect waves-light btn pr-index-item-variants js-pr-index-item-variants" data-variants='{{ price_rule.entitled_variant_ids }}'>Variants List</div></td>
          <td class="">
            <a href="{% url 'pricerules:delete' price_rule.id %}" class="waves-effect waves-light btn pr-index-item-delete js-pr-index-item-delete">Delete</a>
            <a href="{% url 'pricerules:update' price_rule.id %}" class="waves-effect waves-light btn pr-index-item-update">Edit</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <h6><a href="{% url 'pricerules:create' %}" class="waves-effect waves-light btn pr-index-item-create">Create New Price Rule</a></h6>
  {{success}}

{% endblock %}

pricerules/templates/pricerules/update.html
{% extends 'base.html' %}

Update price Rule
<form class=""  method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" name="" value="update">
</form>